// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
import 'package:flutter_dotenv/flutter_dotenv.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY'] ?? 'AIzaSyAAp_V2UD3jk22nI8Ija7wrb1LvVki4y0U',
    appId: dotenv.env['FIREBASE_APP_ID'] ?? '1:299462715471:web:73d05c6102875d2507e23a',
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID'] ?? '299462715471',
    projectId: dotenv.env['FIREBASE_PROJECT_ID'] ?? 'route-hive-53a5e',
    authDomain: dotenv.env['FIREBASE_AUTH_DOMAIN'] ?? 'route-hive-53a5e.firebaseapp.com',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET'] ?? 'route-hive-53a5e.firebasestorage.app',
    measurementId: dotenv.env['FIREBASE_MEASUREMENT_ID'] ?? 'G-QQFM5KQ2Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA59ZwCDViOzbWkmZCLvRXSC2zXCgD89q4',
    appId: '1:299462715471:android:a898271b90b4406107e23a',
    messagingSenderId: '299462715471',
    projectId: 'route-hive-53a5e',
    storageBucket: 'route-hive-53a5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyKfvsniH-PpW6mABGdn4sOfRbz2zvaOk',
    appId: '1:299462715471:ios:a9870957732c0b3b07e23a',
    messagingSenderId: '299462715471',
    projectId: 'route-hive-53a5e',
    storageBucket: 'route-hive-53a5e.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyKfvsniH-PpW6mABGdn4sOfRbz2zvaOk',
    appId: '1:299462715471:ios:a9870957732c0b3b07e23a',
    messagingSenderId: '299462715471',
    projectId: 'route-hive-53a5e',
    storageBucket: 'route-hive-53a5e.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAp_V2UD3jk22nI8Ija7wrb1LvVki4y0U',
    appId: '1:299462715471:web:dcf739deadcd2dcc07e23a',
    messagingSenderId: '299462715471',
    projectId: 'route-hive-53a5e',
    authDomain: 'route-hive-53a5e.firebaseapp.com',
    storageBucket: 'route-hive-53a5e.firebasestorage.app',
    measurementId: 'G-4NMRQBRVYV',
  );
}
